name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  docker:
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:sid
          - debian:bullseye
          - ubuntu:jammy
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-latest
    steps:
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/build-push-action@v2
      with:
        platforms: ${{matrix.platform}}
        build-args:
          IMAGE=${{matrix.image}}
